//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class CourseDetail {
        protected global::System.Web.UI.WebControls.Button btnEnroll;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl courseProgressBar;
        protected global::System.Web.UI.WebControls.Literal litCatBadge;
        protected global::System.Web.UI.WebControls.Literal litCourseDesc;
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;
        protected global::System.Web.UI.WebControls.Literal litDuration;
        protected global::System.Web.UI.WebControls.Literal litEnrolled;
        protected global::System.Web.UI.WebControls.Literal litIcon;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Literal litProgressPct;
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlEnrollBtn;
        protected global::System.Web.UI.WebControls.Panel pnlEnrolled;
        protected global::System.Web.UI.WebControls.Panel pnlLoginForQuiz;
        protected global::System.Web.UI.WebControls.Panel pnlLoginToEnroll;
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuizzes;
        protected global::System.Web.UI.WebControls.Panel pnlNoResources;
        protected global::System.Web.UI.WebControls.Panel pnlProgress;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Repeater rptResources;
        protected global::System.Web.UI.WebControls.Repeater rptStories;
        protected global::System.Web.UI.WebControls.Panel pnlNoStories;
        protected global::System.Web.UI.WebControls.Panel pnlShareStory;
        protected global::System.Web.UI.WebControls.Panel pnlStoryError;
        protected global::System.Web.UI.WebControls.Panel pnlEncourageQuiz;
        protected global::System.Web.UI.WebControls.Literal litStoryError;
        protected global::System.Web.UI.WebControls.TextBox txtStoryName;
        protected global::System.Web.UI.WebControls.TextBox txtAchievement;
        protected global::System.Web.UI.WebControls.TextBox txtWhatLearned;
        protected global::System.Web.UI.WebControls.TextBox txtResult;
        protected global::System.Web.UI.WebControls.Button btnSubmitStory;
    }
}
