//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class CourseList {
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevel;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
    }
}
