//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class QuizPage {
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.HiddenField hdnQuizID;
        protected global::System.Web.UI.WebControls.HiddenField hdnTotalQuestions;
        protected global::System.Web.UI.WebControls.Literal litPassingScore;
        protected global::System.Web.UI.WebControls.Literal litQuestionCount;
        protected global::System.Web.UI.WebControls.Literal litQuizDesc;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.Control ScriptContent;
    }
}
