//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class QuizResults {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divScoreCircle;
        protected global::System.Web.UI.WebControls.HyperLink hlCourse;
        protected global::System.Web.UI.WebControls.HyperLink hlRetake;
        protected global::System.Web.UI.WebControls.Label lblPassFailBadge;
        protected global::System.Web.UI.WebControls.Literal litCorrect;
        protected global::System.Web.UI.WebControls.Literal litFeedback;
        protected global::System.Web.UI.WebControls.Literal litIncorrect;
        protected global::System.Web.UI.WebControls.Literal litPercentage;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litResultLabel;
        protected global::System.Web.UI.WebControls.Literal litScore;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlReview;
        protected global::System.Web.UI.WebControls.Repeater rptReview;
    }
}
