//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class DefaultPage {
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlCTAGuest;
        protected global::System.Web.UI.WebControls.Panel pnlCTAUser;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
