//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class RegisterPage {
        protected global::System.Web.UI.WebControls.Button btnRegister;
        protected global::System.Web.UI.WebControls.CustomValidator cvUsername;
        protected global::System.Web.UI.WebControls.CustomValidator cvEmail;
        protected global::System.Web.UI.WebControls.CustomValidator cvPassword;
        protected global::System.Web.UI.WebControls.CustomValidator cvConfirmPassword;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;
        protected global::System.Web.UI.Control ScriptContent;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
    }
}
