//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class SiteMaster {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMain;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.WebControls.Label lblNavName;
        protected global::System.Web.UI.WebControls.LinkButton lbtnAdminLogout;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.Panel pnlAdminNav;
        protected global::System.Web.UI.WebControls.Panel pnlGuestNav;
        protected global::System.Web.UI.WebControls.Panel pnlUserNav;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptContent;
    }
}
