//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class DiscussionsPage {
        // Messages
        protected global::System.Web.UI.WebControls.Panel pnlMsg;
        protected global::System.Web.UI.WebControls.Literal litMsg;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;

        // Search & Sort
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;

        // Hidden state
        protected global::System.Web.UI.WebControls.HiddenField hdnPage;
        protected global::System.Web.UI.WebControls.HiddenField hdnSort;
        protected global::System.Web.UI.WebControls.HiddenField hdnSearch;
        protected global::System.Web.UI.WebControls.HiddenField hdnPostID;
        protected global::System.Web.UI.WebControls.HiddenField hdnEditCommentID;

        // Post detail panel
        protected global::System.Web.UI.WebControls.Panel pnlPostDetail;
        protected global::System.Web.UI.WebControls.Button btnBackToList;
        protected global::System.Web.UI.WebControls.Literal litResolvedBadge;
        protected global::System.Web.UI.WebControls.Literal litPostTitle;
        protected global::System.Web.UI.WebControls.Literal litPostAuthor;
        protected global::System.Web.UI.WebControls.Literal litPostDate;
        protected global::System.Web.UI.WebControls.Literal litPostViews;
        protected global::System.Web.UI.WebControls.Literal litEditedLabel;
        protected global::System.Web.UI.WebControls.Literal litPostContent;

        // Post owner actions
        protected global::System.Web.UI.WebControls.Panel pnlPostOwnerActions;
        protected global::System.Web.UI.WebControls.Button btnEditPost;
        protected global::System.Web.UI.WebControls.Button btnDeletePost;
        protected global::System.Web.UI.WebControls.Button btnToggleResolved;

        // Edit post form
        protected global::System.Web.UI.WebControls.Panel pnlEditPost;
        protected global::System.Web.UI.WebControls.TextBox txtEditTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEditTitle;
        protected global::System.Web.UI.WebControls.TextBox txtEditContent;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEditContent;
        protected global::System.Web.UI.WebControls.Button btnSaveEdit;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        // Comments repeater
        protected global::System.Web.UI.WebControls.Literal litCommentCount;
        protected global::System.Web.UI.WebControls.Repeater rptComments;
        protected global::System.Web.UI.WebControls.Panel pnlNoComments;

        // Edit comment form
        protected global::System.Web.UI.WebControls.Panel pnlEditComment;
        protected global::System.Web.UI.WebControls.TextBox txtEditComment;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEditComment;
        protected global::System.Web.UI.WebControls.Button btnSaveEditComment;
        protected global::System.Web.UI.WebControls.Button btnCancelEditComment;

        // Add reply
        protected global::System.Web.UI.WebControls.Panel pnlAddComment;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvComment;
        protected global::System.Web.UI.WebControls.Button btnAddComment;
        protected global::System.Web.UI.WebControls.Panel pnlLoginToReply;

        // Posts list
        protected global::System.Web.UI.WebControls.Panel pnlPostsList;
        protected global::System.Web.UI.WebControls.Repeater rptPosts;
        protected global::System.Web.UI.WebControls.Panel pnlPagination;
        protected global::System.Web.UI.WebControls.Button btnPrevPage;
        protected global::System.Web.UI.WebControls.Literal litCurrentPage;
        protected global::System.Web.UI.WebControls.Literal litTotalPages;
        protected global::System.Web.UI.WebControls.Button btnNextPage;

        // Sidebar — profile
        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        protected global::System.Web.UI.WebControls.Literal litProfileName;
        protected global::System.Web.UI.WebControls.Literal litProfileUsername;
        protected global::System.Web.UI.WebControls.Literal litProfilePostCount;
        protected global::System.Web.UI.WebControls.Literal litProfileJoinDate;

        // Sidebar — create post
        protected global::System.Web.UI.WebControls.Panel pnlCreatePost;
        protected global::System.Web.UI.WebControls.TextBox txtPostTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPostTitle;
        protected global::System.Web.UI.WebControls.TextBox txtPostContent;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPostContent;
        protected global::System.Web.UI.WebControls.Button btnCreatePost;
        protected global::System.Web.UI.WebControls.Panel pnlGuestPrompt;
    }
}
