//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace.User {
    public partial class NotificationPreferences {
        protected global::System.Web.UI.WebControls.Panel pnlSaved;
        protected global::System.Web.UI.WebControls.CheckBox chkCourseUpdates;
        protected global::System.Web.UI.WebControls.CheckBox chkDiscussionReplies;
        protected global::System.Web.UI.WebControls.CheckBox chkWeeklyDigest;
        protected global::System.Web.UI.WebControls.CheckBox chkQuizReminders;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
