//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace.User {
    public partial class PrivacySettings {
        protected global::System.Web.UI.WebControls.Panel pnlSaved;
        protected global::System.Web.UI.WebControls.CheckBox chkPublicProfile;
        protected global::System.Web.UI.WebControls.CheckBox chkShowProgress;
        protected global::System.Web.UI.WebControls.CheckBox chkShowForumActivity;
        protected global::System.Web.UI.WebControls.CheckBox chkAnalytics;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
