//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class ProgressTracking {
        // Stats
        protected global::System.Web.UI.WebControls.Literal litOverallPct;
        protected global::System.Web.UI.WebControls.Literal litQuizzesDone;
        protected global::System.Web.UI.WebControls.Literal litForumCount;
        protected global::System.Web.UI.WebControls.Literal litHours;

        // Course progress
        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;
        protected global::System.Web.UI.WebControls.Repeater rptCourseProgress;

        // Chart
        protected global::System.Web.UI.WebControls.Panel pnlNoChart;
        protected global::System.Web.UI.WebControls.Panel pnlChart;
        protected global::System.Web.UI.WebControls.HiddenField hdnChartData;

        // Activity timeline
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;

        // Quiz performance
        protected global::System.Web.UI.WebControls.Literal litAvgScore;
        protected global::System.Web.UI.WebControls.Literal litBestScore;
        protected global::System.Web.UI.WebControls.Literal litQuizzesPassed;
        protected global::System.Web.UI.WebControls.Literal litPassRate;

        // Class comparison
        protected global::System.Web.UI.WebControls.Literal litComparison;

        // Achievements
        protected global::System.Web.UI.WebControls.Literal litAchievements;

        protected global::System.Web.UI.Control MainContent;
        protected global::System.Web.UI.Control ScriptContent;
    }
}
