//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace.User {
    public partial class ReportBug {
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.TextBox txtReport;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReport;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
