//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class UserHome {
        // Welcome banner
        protected global::System.Web.UI.WebControls.Literal litAvatarInitial;
        protected global::System.Web.UI.WebControls.Literal litWelcome;
        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        // Stats
        protected global::System.Web.UI.WebControls.Literal litEnrolled;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Literal litQuizzesTaken;
        protected global::System.Web.UI.WebControls.Literal litForumPosts;

        // Enrolled courses
        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;
        protected global::System.Web.UI.WebControls.Repeater rptEnrolled;

        // Certificates
        protected global::System.Web.UI.WebControls.Panel pnlCertificates;
        protected global::System.Web.UI.WebControls.Literal litCertCount;
        protected global::System.Web.UI.WebControls.Repeater rptCertificates;

        // Discussion activity
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;

        // Quiz results
        protected global::System.Web.UI.WebControls.Panel pnlNoQuizzes;
        protected global::System.Web.UI.WebControls.Repeater rptQuizResults;

        // Profile card
        protected global::System.Web.UI.WebControls.Literal litProfileInitial;
        protected global::System.Web.UI.WebControls.Literal litProfileName;
        protected global::System.Web.UI.WebControls.Literal litProfileUsername;
        protected global::System.Web.UI.WebControls.Panel pnlBio;
        protected global::System.Web.UI.WebControls.Literal litProfileBio;

        // Achievements
        protected global::System.Web.UI.WebControls.Literal litAchievements;

        protected global::System.Web.UI.Control MainContent;
    }
}
