//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSpace {
    public partial class AdminHome {
        protected global::System.Web.UI.WebControls.GridView gvCourses;
        protected global::System.Web.UI.WebControls.GridView gvRecentUsers;
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Literal litTotalCourses;
        protected global::System.Web.UI.WebControls.Literal litTotalEnrollments;
        protected global::System.Web.UI.WebControls.Literal litTotalPosts;
        protected global::System.Web.UI.WebControls.Literal litTotalUsers;
        protected global::System.Web.UI.Control MainContent;
    }
}
